### ISSUE TITLE
[BUG] System.Exception: Signature does not match!

### ISSUE THREAD

**Issue by relasdas** [pizzaboxer/bloxstrap#1016]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

i keep getting System.Exception: Signature does not match! even after i restarted my computer 
[Bloxstrap_20231206T104558Z.log](https://github.com/pizzaboxer/bloxstrap/files/13581136/Bloxstrap_20231206T104558Z.log)

**Comment by pizzaboxer** [comment]
Does the normal Roblox launcher work? Sometimes it might, check if it does.

**Comment by pizzaboxer** [comment]
Actually, that's not a good question since Roblox last updated about a week ago. I'll just let you know that I won't be able to help you much, until the Roblox launcher stops working for you which would happen the next time Roblox updates, at which point you can ask me for help to get Roblox temporarily working again. Though, we are working on implementing a potential fix for this soon.

For now, if you really want to use Bloxstrap, the only advice I can give is to check every few days on whether it works or not.

Other than that, I won't have much to give you, other than telling you to stick to the Roblox launcher for now, so I'll close this. Though, again, I may be able to help you out if the Roblox launcher stops working.
