### ISSUE TITLE
[BUG] multiple account joining issue

### ISSUE THREAD

**Issue by seithk** [pizzaboxer/bloxstrap#1068]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

so basicly it will make both of the accounts say teleporting to restricted place when going to a different place when i have 2 accounts playing roblox

**Comment by Walter-o** [comment]
I have some more information about this bug.

Any time a new roblox instance is started while another is active, a few things happen:
- All clients (except the most recent) have their session sort of invalidated (most likely a file like RobloxCookies.dat being overwritten)
- They can't use teleports, neither client-sided nor server-sided
- They can't purchase things with robux (game just loops at loading)
- They can't invite friends in-game
- Some assets are unloadable due to the broken session and causes immense client console log spam that results in the game eventually slowing to 5 FPS

It would be an insanely good thing if a fix could be found for this.
Roblox caused this bug around 2021 i believe, it just shipped in a random update.

**Comment by pizzaboxer** [comment]
You need to switch accounts inside the desktop app, not on the website.
