### ISSUE TITLE
[BUG] ''Allow multi-instance launching'' isn't working

### ISSUE THREAD

**Issue by shinykazoo** [pizzaboxer/bloxstrap#1115]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

The ''Allow multi-instance launching'' isn't working, I installed the new version but it doesn't work

**Comment by pizzaboxer** [comment]
Well, what happens when you try to launch multiple instances?

**Comment by EmmaScripted** [comment]
> Well, what happens when you try to launch multiple instances?

it's extremely unreliable, sometimes it works then the other times it replaces the current instance with the new one. The only way to currently "fix" it is to disable it and enable it again

**Comment by pizzaboxer** [comment]
It can be picky about how it works (since there's a lot of things that could go wrong with trying to make it work, I'm planning to heavily improve that soon). In the next event that you find it doesn't work for you, let me know and send your entire Bloxstrap logs folder to see if I can find something that's wrong.

**Comment by pizzaboxer** [comment]
Assuming this has been resolved, please comment if it hasn't.
