### ISSUE TITLE
[REQ] Hide fast flags editor for ordinary users

### ISSUE THREAD

**Issue by bluepilledgreat** [pizzaboxer/bloxstrap#1169]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Bad fast flags are the cause of most user problems. Hide the editor for non-power users and add more fast flag presets to compensate.

**Comment by pizzaboxer** [comment]
To preface, the flag editor was added way back in July, back when the userbase was much smaller and I was still adjusted to it being nothing more than a small hobby project, and so at the time I was under the impression that whoever went out of their way to use something like Bloxstrap would know what they were doing. That's why it's so prominently advertised as a feature.

Clearly, that isn't really the case anymore.

One big problem was that the flag editor was intended to be a way for people to configure useful things that people had discovered that weren't provided as presets, especially with presets hard-baked into every version. We need to find a way to make the preset system more dynamic if we want to fully solve this problem, but WPF is going to be a pain in the ass to deal with.

**Comment by d44df016fe28bc8d5974** [comment]
> so we can better hide it away for ordinary users who really should not be using it.
can you make the debug options public
![Screenshot_1](https://github.com/pizzaboxer/bloxstrap/assets/76769061/b8204a6f-3a20-4764-93f4-2e3ee49e10c4)

**Comment by pizzaboxer** [comment]
no

**Comment by GoingCrazyDude** [comment]
based update

**Comment by bluepilledgreat** [comment]
closed because of recent updates
