### ISSUE TITLE
Wine and Bloxstrap

### ISSUE THREAD

**Issue by borjita2019** [pizzaboxer/bloxstrap#117]
I want this app for linux, and think it would be easy if this just wasn't an UWP app.

If there's any easy way possible, can you make a linux native version or just a non-UWP alternative? Most of these features i saw were cool but don't want my pc exploding with Windows.

Edit 1: just realized this MAY NOT be an UWP app and might just be the ui

**Comment by Extravi** [comment]
The user interface is WPF, so it's a Wine issue.

**Comment by pizzaboxer** [comment]
For working with Wine, I'll take a look at that since I feel like that at the very least should work with no problems. If there are problems, I'll try to make something work.

For a native Linux binary, of course that would be a lot more work. Porting over the actual bootstrapper code should be simple, the major pain point would be the user interface since I'm using WinForms and WPF, which are specific to Windows only, so I'd have to port over to something like Avalonia or Qt. It's kind of annoying since I just finished fully porting over to WPF in the 2.0 update, and this would mean having to port over to another UI framework. But if I could pull it off, hopefully it would also pave the road to Mac compatibility too.

**Comment by pizzaboxer** [comment]
Huh, the only problem I'm running into is that Bloxstrap can't detect that the .NET 6 runtime is installed, and I don't know why.
![image](https://user-images.githubusercontent.com/41478239/227460174-443184d3-a96d-4c4f-a501-a2a1be10c8a1.png)

**Comment by pizzaboxer** [comment]
Oh yeah, I'll close this for now since this isn't really a prime concern. If I ever come across anything, I'll put it here.

**Comment by iFlxy** [comment]
Is there a way to bypass that message?

**Comment by pizzaboxer** [comment]
I have no idea, it seems to just work for some people, so meh.

**Comment by Extravi** [comment]
Does Roblox on Linux work with Byfron at all yet, or is it still a no? 
![Screenshot_20230827_144905](https://github.com/pizzaboxer/bloxstrap/assets/98912029/61e75532-fc7b-49cd-a6cf-f91b837f9382)

**Comment by GoingCrazyDude** [comment]
@Extravi yes it works ive tested on the channels zintegration and zcanary

**Comment by pizzaboxer** [comment]
> Does Roblox on Linux work with Byfron at all yet, or is it still a no?

https://devforum.roblox.com/t/why-did-roblox-stop-supporting-linux-users/2444335/109?u=xtremeguy2256

**Comment by Extravi** [comment]
alright thats interesting 

> @Extravi yes it works ive tested on the channels zintegration and zcanary

**Comment by Extravi** [comment]
@pizzaboxer check telegram

**Comment by Noobz4Life** [comment]
I think I found a way to somewhat make it launch?

I installed the [ASP.NET Core Runtime hosting bundle](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-aspnetcore-6.0.21-windows-hosting-bundle-installer) and launched the installer by launching a terminal in my downloads folder and putting in the command
`DOTNET_ROOT="~/.wine/drive_c/Program Files/dotnet/host/fxr/6.0.21/hostfxr.dll" wine BloxStrap-v2.5.2.exe`

This allowed me to successfully launch and install BloxStrap, however you require the environment variable every time so it's not ideal. I imagine you can probably fix it by editing the Wine prefixes registry.
