### ISSUE TITLE
Where is The Rendering Mode Option?

### ISSUE THREAD

**Issue by Leololgithub** [pizzaboxer/bloxstrap#1171]
My game is running worse i think its because its set to Directx 11 and i cant find the option. How do i change it?

**Comment by ShadowCodeX-debug** [comment]
It was removed in a previous update.

**Comment by pizzaboxer** [comment]
See the latest version release notes for why it was removed. You can still change it yourself manually through the FastFlag editor though. Here's some info I posted in the Discord server.

----

I'm placing this here since despite changing this causing instability for the majority of users, some people may still want to use these. These will very likely be added back as preset options in a future version, so here's this for now.

Please note: if you choose to use Vulkan, be mindful that it will very likely break Roblox. If Roblox stops working, try removing the flag for it.

To choose a rendering mode, simply add a flag with the corresponding flag name, and set its value to 'True'. Without any of these set, Direct3D 11 is used by default.

Direct3D 10: `FFlagDebugGraphicsPreferD3D11FL10`
OpenGL: `FFlagDebugGraphicsPreferOpenGL`
Vulkan: `FFlagDebugGraphicsPreferVulkan`
