### ISSUE TITLE
Roblox-Client-Optimizer Flags

### ISSUE THREAD

**Issue by he3als** [pizzaboxer/bloxstrap#121]
An option to automatically download and apply [Roblox-Client-Optimizer](https://github.com/L8X/Roblox-Client-Optimizer) client flags would be good, here's the benefits it has:

- Unlocks FPS (For most people)
- Optimizes Caching
- Optimizes Graphics
- Optimizes Textures
- Increases user privacy
- (May change) Disables the V3 ingame menu
- Disables Crashpad / Backtrace crash metrics
- Disables a large portion of client telemetry
- Disables AbuseReportScreenshot
- Enables font and texture item preloading
- Enables memory prioritization and performance control
- Enables FULL graphics quality options (21 instead of 10!)
- Enables QuickGameLaunch
- Enables ParallelHumanoidManager
- Enables BatchAssetApi

**Comment by he3als** [comment]
I don't think it would be suitable to make these a replacement for rbxfpsunlocker, as rbxfpsunlocker is much more customisable and reliable. I think that a GUI FastFlag editor would be a useful feature, you can extract FastFlags using this command `RobloxStudioBeta.exe -startEvent FFlagExtract -showEvent NoSplashScreen` with Roblox Studio, which puts the flags into the root of the regular Roblox AppData directory I think.

**Comment by pizzaboxer** [comment]
I was considering using the flag because the idea is that the flag *should* be more reliable than using an unlocker (done by the actual rendering engine itself vs done externally by editing memory), and it would reduce an additional dependency that has to be checked for updates, etc. There's not really anything rbxfpsunlocker does more than setting the flag does.
Just so I know, are there any cases of the flag not working where rbxfpsunlocker does?

**Comment by he3als** [comment]
Not sure, but I would say to keep Roblox FPS Unlocker as an option as you can manually specify and cap the FPS.

**Comment by pizzaboxer** [comment]
You can also specify the cap with the flag - it's an FInt flag.

**Comment by he3als** [comment]
Oh, maybe it would be fine then, but I think that it should be properly tested first as on the repo it says that it might not work for everyone.

**Comment by apprehensions** [comment]
off-topic:

> I'm thinking about replacing rbxfpsunlocker with the FPS flag

https://github.com/vinegarhq/vinegar/commit/78f57cf0695d97dcae1c100f8ba64d9f2071faf3

**Comment by he3als** [comment]
Yeah, keeping the code stashed for Roblox FPS Unlocker would be good

**Comment by EasternBloxxer** [comment]
> Found these a few days ago, I can make an option to easily add these. I'm thinking about replacing rbxfpsunlocker with the FPS flag, but you mentioned that it only works for most people?
> Also a bit unrelated, but I'm wondering if a FastFlag editor GUI is worth adding, since just editing the JSON file with a text editor should be sufficient and flexible enough.
Studio like FFlag editor would be neat. Currently I'm usin vscode for editing them.

**Comment by pizzaboxer** [comment]
So I've been taking a look at these and I probably won't add these. Or at least, not fully. I (and others) have expressed concern over many of the rendering-related flags that these configure for the sake of optimization. It modifies a lot of flags (almost 250 of them), and [doesn't really explain why it configures what it does](https://github.com/L8X/Roblox-Client-Optimizer/issues/33). It has good intentions, but because of this it seems to lead to instability ([this](https://github.com/L8X/Roblox-Client-Optimizer/issues/4
) and [this](https://github.com/L8X/Roblox-Client-Optimizer/issues/21) are a few examples).

I mean not fully as I'm planning to add more FastFlag mod presets - some of which are in RCO (like the TaskScheduler FPS cap, 0-21 graphics levels, etc.). See #125 for that. If you want to add a select few flags from RCO that help with making a difference and are stable, feel free to.

**Comment by he3als** [comment]
I think that not having the full thing, but I agree that extracting certain useful sets of flags (e.g. disabling telemetry, unlocking FPS) would be useful.

**Comment by pizzaboxer** [comment]
Reopening this as while they can potentially be unstable, if the user knows about that then it's mostly fine. Other than that, it makes a good addition to the FastFlag mod preset update.

**Comment by pizzaboxer** [comment]
Honestly, the more I look at this, the worse it gets. @bluepilledgreat and others can definitely see where I'm coming from with this. This probably isn't work official support. The option of just adding the flags to Bloxstrap manually still exists, so if you really want to, which I don't recommend, go ahead and do it that way.

**Comment by stan2474** [comment]
> Honestly, the more I look at this, the worse it gets. @bluepilledgreat and others can definitely see where I'm coming from with this. I don't think this is worth officially supporting. The option of just adding the flags to Bloxstrap manually still exists, so if you really want to, which I don't recommend, go ahead and do it that way.

this decision LGTM
