### ISSUE TITLE
[BUG] broken and cant play roblox

### ISSUE THREAD

**Issue by averagetsbrobloxplayer** [pizzaboxer/bloxstrap#1296]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When i used bloxstrap (roblox mod) after that i had fun but when i deleted roblox and installing it again, after that i tried to open roblox but it doesn't work anymore

**Comment by averagetsbrobloxplayer** [comment]
I cant play roblox anymore bruh

**Comment by pizzaboxer** [comment]
Were you trying to reinstall with the original launcher?

**Comment by reakware** [comment]
> Were you trying to reinstall with the original launcher?

How I understand this, is after the new update in late 2023 (that could have been Hyperion), it has recently started detecting alot of non-malicious programs  (Unless its like an injector of some sort), and then running Roblox as a background process, and even if you delete those malicious programs it will still refuse to open because it has already corrupted its own cache files.
There aren't alot of fixes that work but if you know how to solve this issue, let me know (because im having the same issue rn).

**Comment by reakware** [comment]
note: deleting cache files might not work for some reason for people having this issue so if you know a different way (other than downloading microsoft roblox) lmk

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
