### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Uso55** [pizzaboxer/bloxstrap#1378]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

hi, i have a problem every time i open roblox it says "Sens Apii" or  "Sens" error, i have this issue for almost 2 years now, if u can help pls reply on my e-mail: dunamaty@gmail.com

**Comment by moonleaks** [comment]
why would you put your email and what is sens apii, i would reset your pc but keep personal files

**Comment by Uso55** [comment]
It's some dill file


Dne so 2. 3. 2024 18:55 uživatel moon ***@***.***> napsal:

**Comment by pizzaboxer** [comment]
For almost two years? I somehow doubt that.

The only thing I can suggest to you to fix it is to do a repair of your Windows system files. You can do that by opening a Command Prompt as Administrator, and running the two commands in the order specified:
```
dism /online /cleanup-image /restorehealth
sfc /scannow
```

Because this is an issue with Roblox itself and not Bloxstrap, there's not much else that I can do to help you.
