### ISSUE TITLE
[BUG] unexpected client behavior

### ISSUE THREAD

**Issue by theAK9** [pizzaboxer/bloxstrap#1399]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?
unexpected client behavior

idk i js play normally like i use to and something happened while i was continuing server hopping and then when i wanted to play the error pop up

**Comment by NinDevs** [comment]
Try disabling multi-instance if you have that on, and keep your FPS cap below anything exaggerative (120-165 seems like a sweet spot) since Roblox seems to become a lot more prone to crashing with high FPS caps. Also, try having the disable the desktop app feature off if you have that on. I toggled this off recently due to Roblox insta closing on me a few times w Bloxstrap and now it seems fine.

**Comment by pizzaboxer** [comment]
Multi-instance launching shouldn't be causing it.

Do you get this error every time you try launching Roblox?

**Comment by vigatu** [comment]
Same story with me. Already like 4th time seeing this error after some time of server hopping while having another account open at the same time with multi-instance option on. It seems like nothing helps but just waiting for, like, an hour for it error to go away. Before, server hopping without Bloxstrap didn't seem to cause any issues. I would assume this problem occurs only when doing exactly that, because normally everything is fine and working for me.
![Screenshot_11](https://github.com/pizzaboxer/bloxstrap/assets/130851129/c81050bc-682a-4b2f-ab4a-f3ed2ad3b900)

**Comment by pizzaboxer** [comment]
Have you never encountered this error when having only one instance open?

**Comment by vigatu** [comment]
While using Bloxstrap, I've been running only 2 instances of Roblox at once, so

**Comment by vigatu** [comment]
Oh, it might be something not related to Bloxstrap after all, since I just deleted it but received this error once again. That's very confusing to me now. I never had this happen before installing Bloxstrap recently so I was absolutely certain that this is the reason.  I guess it might something on the Roblox end or even on my own.
