### ISSUE TITLE
(feature request)More languages support

### ISSUE THREAD

**Issue by KaneDbD** [pizzaboxer/bloxstrap#141]
Would it be possible for you to add more languages for Bloxstrap Menu app? People would contribute to your project, and I think it would be kinda useful, some people who don't know English very well could use Bloxstrap.

**Comment by pizzaboxer** [comment]
Yeah, I've never really tried adding localization to an application, but I could definitely do it. I'm kind of just wondering whether Bloxstrap is popular enough for this to be a concern, and so whether it's worth doing this, especially since everything about it online (at least right now) is English only. If this actually gets some use/attention with non-English people, I could add it. For now though, I'm not really seeing this as worthwhile.
