### ISSUE TITLE
Context menu items for the tray icon

### ISSUE THREAD

**Issue by nakoyasha** [pizzaboxer/bloxstrap#186]
aka making the tray icon actually useful by adding items like
- copying the Job ID/game link
- discord rpc toggle **(?)**
- opening the latest log file **(?)**

**Comment by pizzaboxer** [comment]
Oh, those are some nice ideas for context menu items.

**Comment by pizzaboxer** [comment]
I'm abandoning this idea, because I don't think it's actually possible to do with the way this program is made. Annoyingly, the notification area icon is a WinForms component only, so its smoothness with WPF/non-GUI applications is kind of hit and miss. I barely managed to make toast notifications work, and that's one of the most simple components of it. A context menu, on the other hand is only going to work in a pure-GUI application, which this is not. I tried it, but it just freezes when the bootstrapper thread takes over.

**Comment by pizzaboxer** [comment]
i might be stupid because i just realized a way to make this work

**Comment by nakoyasha** [comment]
💀

**Comment by pizzaboxer** [comment]
and i managed to make it work

![image](https://github.com/pizzaboxer/bloxstrap/assets/41478239/b2c8a1ba-16fe-42ff-9253-bd1080fe9959)
