### ISSUE TITLE
[BUG] reshade doesnt work with bloxstrap

### ISSUE THREAD

**Issue by Spacyaa** [pizzaboxer/bloxstrap#1917]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

plis help

**Comment by X1kera** [comment]
Obviously, Reshade or Roshade will not work due to the new anti-cheat measures implemented by the Roblox team. 
(The Anti-Cheat is called - Hyperion 4.0)
If you attempt to inject or start something before the game, such as executing code or injecting modifications, the game will immediately close without warning or whatsoever.
For the future of Roblox, finding a bypass to inject something again would be a win for the community. However, currently, we can't do anything except play the normal version of the Roblox Client or use Bloxstrap to play Roblox.

**Comment by pizzaboxer** [comment]
Use [Bloxshade](https://bloxshade.com).

**Comment by Tokiw0-3** [comment]
I wouldn't trust the bloxshade he linked or the github one I found with latest januari update.[https://www.virustotal.com/gui/file/8db4a31b05dec3c5adfc4b7ede9f0d8e4e2eb384524ce829e707c9908492d355/community](url)
