### ISSUE TITLE
Add back multi instance (The only thing carrying bloxstrap imo)

### ISSUE THREAD

**Issue by Kuchkiio** [pizzaboxer/bloxstrap#2021]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

I want multi instanceck back man, eveer since roblox added a max frame rate onto the offical game there really isnt a reason to use blox strap apart from the multi instance. Now there really is not a use for blox strap anymore (IMO)

**Comment by exurd** [comment]
As a workaround, using an old version that includes multi-instance is still possible. When installing, disable the "Automatically update Bloxstrap" setting in the Behaviour tab. I tried this and it downloaded the latest version of Roblox fine.

**Comment by CreacOwo** [comment]
More information found here: https://github.com/pizzaboxer/bloxstrap/wiki/Plans-to-remove-multi%E2%80%90instance-launching-from-Bloxstrap

Still, I find it quite lame that they had to remove it. Not cool.

**Comment by MenacingBlin** [comment]
In my opinion, maybe its because multi instances is considered to be an exploit and its against Roblox's ToS (source is from Google). There's a Roblox exploit called Multi-Roblox which lets users open up multiple Roblox instances on one device and people get banned for using it.

**Comment by someguy192** [comment]
> In my opinion, maybe its because multi instances is considered to be an exploit and its against Roblox's ToS (source is from Google). There's a Roblox exploit called Multi-Roblox which lets users open up multiple Roblox instances on one device and people get banned for using it.

Can you link your source?

**Comment by Clyde-Timonera** [comment]
I believe it was removed to comply with Roblox TOS.

**Comment by someguy192** [comment]
> I believe it was removed to comply with Roblox TOS.

They never said it was removed to comply with Roblox TOS. They said it because it's "pretty niche" and "i don't wanna be involved with this"

**Comment by MenacingBlin** [comment]
> > In my opinion, maybe its because multi instances is considered to be an exploit and its against Roblox's ToS (source is from Google). There's a Roblox exploit called Multi-Roblox which lets users open up multiple Roblox instances on one device and people get banned for using it.
> 
> Can you link your source?

Of course!
https://devforum.roblox.com/t/where-is-a-way-to-use-two-clients-at-the-same-time/2392787/2

and I quote from ganteng (p49p0) in the dev forum reply:
"about that roblox studio has a option to play with multiple accounts, the max is 4 or 5 i think
**but if you want to launch multiple roblox player apps, i dont recommend doing it since you will using an exploit which violates the roblox tos.**"

And here's a Reddit post of someone getting banned for using Multi-Roblox, the multi instance exploit
https://www.reddit.com/r/ROBLOXBans/comments/16i3zqj/just_got_banned_for_using_multi_roblox_was_i_in/

**Comment by someguy192** [comment]
> and I quote from ganteng (p49p0) in the dev forum reply: "about that roblox studio has a option to play with multiple accounts, the max is 4 or 5 i think **but if you want to launch multiple roblox player apps, i dont recommend doing it since you will using an exploit which violates the roblox tos.**"

That's someone saying that, I don't think roblox officially has ever came out and said that multi instance launching is an exploit

 >And here's a Reddit post of someone getting banned for using Multi-Roblox, the multi instance exploit
https://www.reddit.com/r/ROBLOXBans/comments/16i3zqj/just_got_banned_for_using_multi_roblox_was_i_in/

If you check that person's posts, you can see this comment https://www.reddit.com/r/robloxhackers/comments/17iu4a5/comment/k70621p/ which clearly states that they have exploited in the past atleast.

**Comment by MenacingBlin** [comment]
I see. 

Well, I'm out of points now, so I'll just assume that he doesn't want to get involved with the in-game farming thing, like he mentioned in the wiki page that Creac sent.

**Comment by someguy192** [comment]
> Well, I'm out of points now, so I'll just assume that he doesn't want to get involved with the in-game farming thing, like he mentioned in the wiki page that Creac sent.

Yep, that's probably the actual main reason

**Comment by CreacOwo** [comment]
If ROBLOX allows rbxfpsunlocker I don't see why they would not directly allow multiple instances, it's not really an exploit really, I would not consider it one at least, same for rbxfpsunlocker.

**Comment by MenacingBlin** [comment]
> If ROBLOX allows rbxfpsunlocker I don't see why they would not directly allow multiple instances, it's not really an exploit really, I would not consider it one at least, same for rbxfpsunlocker.

Multi instances are harmful for majority of simulator games, but other than that there's not really any harm to other games on Roblox.

Who would launch more than two accounts in an FPS game? Or an adventure RPG game?

**Comment by CreacOwo** [comment]
I could argue that some games run on RenderStepped and that changing the fps may make it faster but honestly I don't feel like arguing, people can already alt despite the tool by just using other computers

**Comment by lokzz** [comment]
cant ppl just re-compile bloxstrap after undoing the changes with like `git revert` :/

**Comment by ILikeDownloading** [comment]
so uhh I did this. But i noticed everytime i close roblox (so "X" it out) it logs me out of my account. And i use a macro for bee swarm. And its very annoying to wake up/come back to me being logged out of my account because roblox crashed. Please help how do i fix this 😭 , and it started happening when i downloaded this. And even though i uninstalled everything related to roblox and bloxstrap off of my computer its still happening

**Comment by ShadowCodeX-debug** [comment]
Multi-instancing will not come back due to the improper use of it. Also even though ROBLOX ToS doesn't explicitly say it's against the rules, doesn't mean it's NOT an exploit. Anyway, please do not use older versions of Bloxstrap.

**Comment by ILikeDownloading** [comment]
I dont use it anymore. I used it at the time. And i dont anymore. And because of it, it would log me out everytime i reopen roblox. Its a slight annoyance, but i can still log back in

**Comment by sodasim123** [comment]
> Multi-instancing will not come back due to the improper use of it. Also even though ROBLOX ToS doesn't explicitly say it's against the rules, doesn't mean it's not an exploit. Anyway, please do not use older versions of Bloxstrap.


"Also even though ROBLOX ToS doesn't explicitly say it's against the rules, doesn't mean it's not an exploit" Well you see, the thing is,

It's not EVEN an exploit. according to the github repository, they removed multi instance simply because "i dont wanna get involved in this", which really makes it sound way serious that it really is.
Multi instance was what made bloxstrap so good and different, simply just removing it for no actual valid reason is a shot in the foot.

Also they broke the older versions because ppl were trying to download them cuz they werent satisfied with the new additions so it doesnt even matter lmfao

**Comment by lokzz** [comment]
> > Also they broke the older versions

bloxstrap didnt "break" the older versions, roblox changed a few files/downloads and the older versions just didnt know

**Comment by ILikeDownloading** [comment]
Oh cool but how do i fix this 😭 i dont have this problem at my dads cause
i use a different computer. But at my moms im now using the website
version. Also, because of this issue i lost an alt account with good adopt
me pets on it

**Comment by andreganteng69** [comment]
> and I quote from ganteng (p49p0) in the dev forum reply: "about that roblox studio has a option to play with multiple accounts, the max is 4 or 5 i think **but if you want to launch multiple roblox player apps, i dont recommend doing it since you will using an exploit which violates the roblox tos.**"

thanks for quoting me lol
anyway, seems like multi roblox instances doesn't appear to be an exploit. If you were launching 2 games **with the same account**, that should count as **exploiting**.
if you use different accounts for each instance, should be ok to go. since you can do the same using virtual machines ig? cus 1 device is made to only launch 1 instance.

sincerely, ganteng
