### ISSUE TITLE
sensapi.dll error

### ISSUE THREAD

**Issue by KonoKore** [pizzaboxer/bloxstrap#208]
After trying to join a game, both me and my little brother are dealing with a "sensapi.dll" error

The only way that I know to fix it is with a total reinstallation

![image](https://user-images.githubusercontent.com/128200152/236480424-c5b08d16-d619-432c-ae53-3a6b0c1cc1b5.png)

**Comment by pizzaboxer** [comment]
That's not my problem, that's a Roblox problem. Though, this is an error that really shouldn't be happening? SensApi.dll is a system file located in System32, there should be no reason that Roblox isn't able to load it. Make sure that Windows is fully up-to-date, and try and see if it can be fixed by running `sfc /scannow` in the Command Prompt as an Administrator.

**Comment by RoboMolluskKing** [comment]
i sometimes get the same error too, how i fixed it myself was first running in an admin cmd `sfc /scannow` 

if it finds any issues, run `DISM /Online /Cleanup-Image /ScanHealth`, and then `DISM /Online /Cleanup-Image /RestoreHealth`

the last command will get stuck, so give it time

**Comment by xyqil** [comment]
came across this error today, searched "sensapi roblox" up, found out that others were having the same problem (as far back as 2 weeks ago even), might just be a byfron problem

once i changed my release channel to zlive, i was able to open the desktop app and get past the error, but joining games just gave me error code 272. no idea whats going on

**Comment by pizzaboxer** [comment]
Have you tried what we were talking about above? Keep your channel as LIVE or you won't be able to join any servers.
