### ISSUE TITLE
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 30 seconds elapsing.  [Inner Exception] System.TimeoutException: A task was canceled.  [Inner Exception] System.Threading.Tasks.TaskCanceledException: A task was canceled.

### ISSUE THREAD

**Issue by XXXkuklus1977** [pizzaboxer/bloxstrap#2091]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 30 seconds elapsing.

[Inner Exception]
System.TimeoutException: A task was canceled.

[Inner Exception]
System.Threading.Tasks.TaskCanceledException: A task was canceled.
what i need to do with this?

**Comment by pizzaboxer** [comment]
Send the log file

**Comment by realeagleFR** [comment]
i have a log file which just shows this: System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 30 seconds elapsing.

[Inner Exception]
System.TimeoutException: A task was canceled.

[Inner Exception]
System.Threading.Tasks.TaskCanceledException: A task was canceled.

**Comment by pizzaboxer** [comment]
Addressed in Wiki
