### ISSUE TITLE
[BUG] idk what happened pls help, how do i fix it 

### ISSUE THREAD

**Issue by DicksonKaiden** [pizzaboxer/bloxstrap#2142]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When i try load a game, bloxstrap gets midway of "upgrading roblox" then crashes
![Uploading Screenshot 2024-06-18 154052.png…]()

**Comment by bluepilledgreat** [comment]
Provide a log file

**Comment by gb799** [comment]
if this wiki is not helpful, then provide more information to this issue. if this is not the same issue (idk because no futher information) then i cant do much help, but here is a wiki if thats the case https://github.com/pizzaboxer/bloxstrap/wiki/Launching-from-different-accounts-always-forces-a-Roblox-upgrade

**Comment by pizzaboxer** [comment]
> When i try load a game, bloxstrap gets midway of "upgrading roblox" then crashes

Crashes in what way? Do you get an error message or does it just close?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
