### ISSUE TITLE
[BUG] System.ComponentModel.Win32Exception: The operation was successfully concluded.

### ISSUE THREAD

**Issue by ImTrep** [pizzaboxer/bloxstrap#2220]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

This exception always happens when I start the game, but it still works normally for now

![image](https://github.com/pizzaboxer/bloxstrap/assets/131490609/bb7cb494-b4d9-4e48-8c79-ea29c5ff35d8)
[log file](https://github.com/user-attachments/files/16057156/Bloxstrap_20240701T173509Z.log)

**Comment by pizzaboxer** [comment]
I'm not really sure what I can do about this because it's happening simply from trying to show a window. It's trying to prompt you for something though, and I'd like to know what it is.

Download this version, run Bloxstrap.exe, click yes when it asks you to upgrade, try and join a game, and upload another log file when the error occurs. 

https://github.com/pizzaboxer/bloxstrap/actions/runs/9756876320/artifacts/1658488678

**Comment by ImTrep** [comment]
I apologise for taking so long to reply, but I finally found the cause of the problem, for some reason the [specialk](https://www.special-k.info/) service was on and trying to inject into roblox, but it seems to conflict with bloxstrap
