### ISSUE TITLE
[BUG] Roblox game does not open on windows 10 LTSC

### ISSUE THREAD

**Issue by Ginger334** [pizzaboxer/bloxstrap#2369]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

so I am having a currently an issue where I'm trying to play Roblox using bloxstrap and game will not open and don't know why also before you ask yes I installed it Windows desktop runtime on my windows and i'm running windows 10 enterprise LTSC 2021

**Comment by Hitter101** [comment]
Hey, I had the same issue. However, the solution is quite a lengthy process of absolutely nothing. Go to your Date & Time settings, set your timezone to your current timezone and click “Sync”. Now here’s the fun part, shutdown your laptop/pc and wait around 8-12 hours. It’s currently the only working solution since Roblox is dumb.

**Comment by pizzaboxer** [comment]
Does it work without? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by Ginger334** [comment]
> Does it work without? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

I also had to issue with normal Roblox but today it worked fine thank you for helping me
