### ISSUE TITLE
[BUG] soundboard and autoclicker not working for bloxstrap

### ISSUE THREAD

**Issue by Slicesofmylife** [pizzaboxer/bloxstrap#2435]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

whenever i use bloxstrap my soundboard and autoclicker dont work, i tried it with normal roblox and they both worked fine on there, ive also tried different keybinds for the soundboard but that doesnt work either, if it helps it works when i alt tab and do it and then go back to bloxstrap roblox.

**Comment by ShadowCodeX-debug** [comment]
Are you sure you don't have any flags that disable Input Audio?

**Comment by pizzaboxer** [comment]
Upload your configuration please: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

This sounds like a difference in expected behavior due to Roblox not being where it's expected to be (at %localappdata%\Roblox), in which case there's nothing that can really be done about that

**Comment by pizzaboxer** [comment]
Issue has stale for over a month, and will be reopened if further information is given.
