### ISSUE TITLE
[REQ] Add an option to change your cursor in bloxstrap

### ISSUE THREAD

**Issue by mathiameatie** [pizzaboxer/bloxstrap#2579]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

I don't know if this is a fastflag thing, but I've seen people do it on the regular roblox client.

**Comment by Roblox-Thot** [comment]
Under mods there are 2 different ones (if you don't count default)

![image](https://github.com/user-attachments/assets/a8eda8b2-d7ac-4552-afb2-abaed1562564)


Otherwise you can add your own by clicking the "open mods folder" button then going to `content`>`textures`>`Cursors`>`KeyboardMouse` and making two files with the image one called "ArrowFarCursor.png" and the other "ArrowCursor.png"

**Comment by ShadowCodeX-debug** [comment]
@pizzaboxer can't you put another button on an option?

**Comment by pizzaboxer** [comment]
We can, and I was planning to do that in the next upcoming version actually. Thanks for reminding me about that.

Duplicate of #1348
