### ISSUE TITLE
[BUG] Graphics Quality Staying the Highest Even If It's the Lowest

### ISSUE THREAD

**Issue by t1mecod3** [pizzaboxer/bloxstrap#2778]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

Recently, an issue i've been experiencing that in Bloxstrap, even if I'm on the lowest graphical setting, it'll still stay the highest. Basically tanking performance. (In this screenshot here it shows sunrays. In this game, unless you have high graphical settings, this isn't visible.)

![image](https://github.com/user-attachments/assets/e4bea97d-18d4-4de8-a857-f0d830f5562e)

![image](https://github.com/user-attachments/assets/864ed4e6-4347-4813-8480-5cd00110a810)

### Bloxstrap Log

N/A

**Comment by RuthlessVerizon** [comment]
its a know roblox issue and they have responded. nothing is wrong with bloxstrap
![image](https://github.com/user-attachments/assets/a89d8a5b-5f0e-4b74-add6-5a6b91c36e0e)

**Comment by I1Il2l** [comment]
Somehow when I launch Roblox without Bloxstrap this doesn't happen but it does when I'm using it. Not my fastflags either since I exported all of them and then deleted them to make sure it wasn't anything I had.
![image](https://github.com/user-attachments/assets/b289435a-f9a8-4806-a37e-fd8d79b7e4e0)
![image](https://github.com/user-attachments/assets/51cedfa4-25cc-4fd6-a2a4-f16f9398de89)

**Comment by NabHeyka22** [comment]
roblox issue
can't be solved

**Comment by t1mecod3** [comment]
Understandable, thank you.
