### ISSUE TITLE
[REQ] ADD BLOXSTRAP FOR LINUX

### ISSUE THREAD

**Issue by SteveThe00** [pizzaboxer/bloxstrap#2835]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

can u create bloxstrap for linux ver

**Comment by coolpeter98** [comment]
if you are talking about Sober then that runs the Android version of Roblox. Bloxstrap is for PC.

**Comment by bluepilledgreat** [comment]
switch to a better operating system

**Comment by v3hn** [comment]
> switch to a better operating system

i'm gonna feed you to lions bro

**Comment by NabHeyka22** [comment]
i mean he is right
why are you even on linux

**Comment by v3hn** [comment]
you wouldn't get it

**Comment by Storm-930** [comment]
no. just no. linux isnt even supposed to be used by the average man. linux roblox is just an adaptation of mobile roblox, with all the bugs and crashing that come with it.
the only good reasons that you'd use linux over windows are
- you're too poor to get windows (how did you come this far in an impoverished family might i ask)
- you're a power user (justifiable)
- you fucked around and now you found out (oh god why)
- you're running anything not named a conventional computer
- you're operating a server
if you don't fit any of the point, just get Windows, even 10 does the job, for the sake of not only us, but you too...

**Comment by pizzaboxer** [comment]
> linux roblox is just an adaptation of mobile roblox

i helped work on that yknow

**Comment by JumpIn-Git** [comment]
> no. just no. linux isnt even supposed to be used by the average man. linux roblox is just an adaptation of mobile roblox, with all the bugs and crashing that come with it. the only good reasons that you'd use linux over windows are
> 
>     * you're too poor to get windows (how did you come this far in an impoverished family might i ask)
> 
>     * you're a power user (justifiable)
> 
>     * you fucked around and now you found out (oh god why)
> 
>     * you're running anything not named a conventional computer
> 
>     * you're operating a server
>       if you don't fit any of the point, just get Windows, even 10 does the job, for the sake of not only us, but you too...

very funny bud, since i switched to linux, i cant even go back to windows out pure disgust

**Comment by JumpIn-Git** [comment]
> i think there was an alternative for bloxstrap on linux (buy a pc that can run windows bru 😭 )

my laptop can still run windows, even if my laptop could easily run windows i would still prefer linux

**Comment by ClairefpeL** [comment]
My laptop still run chrome os but bloxstrap is not going to work on Linux and on chrome os and android.

**Comment by gjehren** [comment]
for anybody finding this in the future, use [Lucem](https://github.com/xTrayambak/lucem)

**Comment by Antonygamergod** [comment]
@gjehren thank you for recomending lucem, sober isnt working properly right now

**Comment by Antonygamergod** [comment]
And just one thing, even though this whole Linux thing is from a year ago, I want to say that I use Linux but I don't judge anyone who uses Windows or Mac, it doesn't matter, there's no need to fight, everything has its ups and downs.

**Comment by gjehren** [comment]
> And just one thing, even though this whole Linux thing is from a year ago, I want to say that I use Linux but I don't judge anyone who uses Windows or Mac, it doesn't matter, there's no need to fight, everything has its ups and downs.

Same. I don't understand the whole "defending your OS" thing. Do whatever you want, not what some dude on the internet says.

**Comment by invencivel7920** [comment]
> switch to a better operating system

Your dumb, linux is better, windows is slow and bad, linux runs even your big ass mother

**Comment by JumpIn-Git** [comment]
> switch to a better operating system

windows is powered by linux btw, nothing u can say lmao

**Comment by Shavixinio** [comment]
Yeah but we're talking about operating systems for personal computers..?

**Comment by JumpIn-Git** [comment]
> Yeah but we're talking about operating systems for personal computers..?

thats not my point... i mean that a big part of ms itself is powered by linux, which proves its superiority.

and linux is getting more and more suitable for personal use. the year of the linux desktop WILL come

**Comment by JumpIn-Git** [comment]
> And just one thing, even though this whole Linux thing is from a year ago, I want to say that I use Linux but I don't judge anyone who uses Windows or Mac, it doesn't matter, there's no need to fight, everything has its ups and downs.

+1!

**Comment by JumpIn-Git** [comment]
> switch to a better operating system

says the guy using a os powered by linux, making a program for it using git (made by the creater of the linux kernel), hosting on github (also linux) using a linux workflow.

**Comment by Beverlyhp20** [comment]
help sober isnt working on my chromebook

**Comment by ReVerseYTReal** [comment]
> switch to a better operating system

rude. very rude.

**Comment by Abusheyh2** [comment]
> i think there was an alternative for bloxstrap on linux (buy a pc that can run windows bru 😭 )

Listening to someone flex about "buying a Windows PC" is like watching a caveman brag about discovering a lukewarm puddle while everyone else is out here splitting atoms. You’re really out here acting like Windows is some high-tier benchmark for hardware, but that "buy a PC" line is just a loud admission that you’re too technologically illiterate to handle anything that doesn’t come with a "Start" button and pre-installed bloatware. 

My laptop could run Windows in its sleep, but why would I lobotomize a perfectly optimized machine just to join the herd of users who let Microsoft treat their privacy like a public park? Suggesting I switch just to run a Roblox wrapper is like telling a surgeon to trade their scalpel for a rusty spoon because it’s easier to hold. You aren't "privileged" for using Windows; you’re just trapped in a gilded cage of telemetry and forced updates because the concept of a kernel makes your brain stall. I’d rather spend ten minutes configuring a compatibility layer than ten seconds being a "Next-Next-Finish" npc who thinks they’ve reached the peak of computing because they can open Chrome without a terminal.

**Comment by Abusheyh2** [comment]
> switch to a better operating system

Suggesting someone "switch to a better operating system" while they're already running a custom Linux kernel is like telling a Formula 1 driver they should consider a minivan because it has more cup holders. You’re flexing a system that’s basically 40% spyware and 60% "Please wait, we’re configuring your updates," acting like it’s the gold standard just because you’re too intimidated by a configuration file. 

My laptop has the horsepower to run your precious Windows without breaking 40°C, but I’m not about to throttle my hardware just so I can have a "user-friendly" experience that treats me like a digital toddler. You think you’re being helpful, but you’re really just announcing that you’re fine with an OS that sells your data, eats your RAM, and forces you into a generic, locked-down workflow. I’d rather deal with the occasional compatibility tweak than spend my life in a bland, bloated environment where the only "customization" you can handle is changing your desktop wallpaper. Stick to your "Better OS" and keep enjoying those forced restarts; some of us actually prefer to own the machines we paid for.

**Comment by Abusheyh2** [comment]
And for those who think i am writing this with AI I AM NOT I AM F*****CKING SERIOUS ABOUT WHAT I AM SAYING
