### ISSUE TITLE
[BUG] ERRO 404

### ISSUE THREAD

**Issue by javi343** [pizzaboxer/bloxstrap#2838]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).

### Bloxstrap Log

NADEJAGUJAR

**Comment by NabHeyka22** [comment]
so number 1: stop putting checks like it's fucking useless to us to figure out your issue
number 2: you did not read through the wiki because the error is written in the wiki
number 3: update bloxstrap and if you want multi instance use roblox account manager and the only official place is on the github. if you don't want to update, we won't help you. if you're using it for exploits, we won't help you either
