### ISSUE TITLE
[BUG] Roblox detecting Bloxstrap and quitting when detected.

### ISSUE THREAD

**Issue by KubaYT106Super** [pizzaboxer/bloxstrap#2967]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

![image](https://github.com/user-attachments/assets/67ede1e4-74bf-4443-aeca-6e8416b71c17)

### Bloxstrap Log

N/A

**Comment by NabHeyka22** [comment]
Bloxstrap is safe and it's not an exploiting tool. It's explained why on the wiki https://github.com/pizzaboxer/bloxstrap/wiki/Why-it's-not-reasonably-possible-for-you-to-be-banned-by-Bloxstrap. The reason the error is happening is because you're most likely using an exploiting tool. And if you are, it's not our problem. Stop exploiting, and get better at games loser.

**Comment by bluepilledgreat** [comment]
Are you sure you don't have any other reverse engineering or cheat applications open?

**Comment by ShadowCodeX-debug** [comment]
Restart your computer. If it persists then uninstall Bloxstrap and restart again. After that reinstall Bloxstrap.

If this doesn't work, you are most likely to be using an Code Injector.

**Comment by KubaYT106Super** [comment]
I'm not using a reverse enginerring or exploiting tool. It's just Bloxstrap. Why does Byfron detect bloxstrap? It's just a roblox launcher that allows the person to do some changes.

**Comment by KubaYT106Super** [comment]
Finally, this has been solved - Probably because Roblox had a update and Bloxstrap didn't do it causing it to crash.
