### ISSUE TITLE
[REQ] add multi instance launching dont just close the request hear me out

### ISSUE THREAD

**Issue by sigma-skibidi-mewing** [pizzaboxer/bloxstrap#3030]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

i really really need multi instance launching i cant do multi player events i have no friends nor do i have siblings i was rlly happy when multi instance launching was first added and then i was devasted when you guys removed it now i cant do any multi player tasks

**Comment by NabHeyka22** [comment]
Just use Roblox account manager then. Pizzaboxer and the devs will probably never add multi instance back, as pizzaboxer said he removed it due to instability.

**Comment by Cheoo21** [comment]
but roblox account manager is a virus

**Comment by NabHeyka22** [comment]
It's not.
The source code is public, you can read that if you want to. It's a false positive.
And any youtuber saying Roblox Account Manager is a virus without proof of the source code, is lying.

**Comment by bluepilledgreat** [comment]
⍙⟒ ⏃⍀⟒ ⋏⍜⏁ ⏃⎅⎅⟟⋏☌ ⋔⎍⌰⏁⟟-⟟⋏⌇⏁⏃⋏☊⟟⋏☌. ⌿⌰⟒⏃⌇⟒ ⌇⏁⍜⌿ ⍜⌿⟒⋏⟟⋏☌ ⏁⊑⟒⌇⟒ ⟟⌇⌇⎍⟒⌇.

**Comment by vvirtues** [comment]
huh
also RAM is now archived

**Comment by Cheoo21** [comment]
> It's not. The source code is public, you can read that if you want to. It's a false positive. And any youtuber saying Roblox Account Manager is a virus without proof of the source code, is lying.

tried out on tria.ge its confirmed a virus

**Comment by Cheoo21** [comment]
https://tria.ge/241015-seflzavekr

roblox account manager, virus? yes

**Comment by Wanwood1** [comment]
> https://tria.ge/241015-seflzavekr
> 
> roblox account manager, virus? yes

No, it is not a virus, if it was, someone would have looked at the source and spread the proof around, and we wouldnt be telling people to use Roblox Account Manager. Antiviruses often give false positives and this is extremely common for every unsigned app, a virus scan isnt proof for open source projects like this.

Im not saying you shouldnt trust virus scans, but antiviruses largely use guesswork to determine if something is a virus or not, like once a popular vietnamese antivirus deleted people's system32 of their computer because it was flagged, or how majority of antiviruses STILL flag basic powershell code and code by Microsoft themselves, you can just paste the code of a open source Microsoft project into powershell and there is a high chance it will get flagged because its again, unsigned.
Of course another example of this is cases like this where RAM, a unsigned app is flagged because they use some same functions that other virus softwares use, they are flagged not just for using these codes that literally most of the time have no harmful use, but because they are UNSIGNED, meaning they do not have the signature of some corporation and so deemed more "untrustworthy" which is why it causes its flagging.
https://www.youtube.com/watch?v=bLDOETBAxnE

**Comment by vvirtues** [comment]
If you don't trust it read the source, download it and build yourself. Something that retains cookies would obviously get flagged, but that's the whole point of the app anyway

**Comment by Cheoo21** [comment]
> > https://tria.ge/241015-seflzavekr
> > roblox account manager, virus? yes
> 
> No, it is not a virus, if it was, someone would have looked at the source and spread the proof around, and we wouldnt be telling people to use Roblox Account Manager. Antiviruses often give false positives and this is extremely common for every unsigned app, a virus scan isnt proof for open source projects like this.
> 
> Im not saying you shouldnt trust virus scans, but antiviruses largely use guesswork to determine if something is a virus or not, like once a popular vietnamese antivirus deleted people's system32 of their computer because it was flagged, or how majority of antiviruses STILL flag basic powershell code and code by Microsoft themselves, you can just paste the code of a open source Microsoft project into powershell and there is a high chance it will get flagged because its again, unsigned. Of course another example of this is cases like this where RAM, a unsigned app is flagged because they use some same functions that other virus softwares use, they are flagged not just for using these codes that literally most of the time have no harmful use, but because they are UNSIGNED, meaning they do not have the signature of some corporation and so deemed more "untrustworthy" which is why it causes its flagging. https://www.youtube.com/watch?v=bLDOETBAxnE There will never be a day where you can trust those antivirus scan websites like triage or virustotal because there will always be a way to get past the security measures of antiviruses. If a file is flagged, it might be a false positive and have no trojan. If a file isnt flagged, it might be a false negative and have actual trojan inside it, since the act of bypassing detection measures of antivirus softwares have been a continous arms race of one side getting one step infront of eachother, just for it to shift sides every time, an arms race that wont end soon.
> 
> Read if you want, ignore if your retarded.

Oh gosh I don't think you understand what triage do... it uses a virtual machine with av off and analyzes what the trojan does to a system with logs and analyzes the viruses behaviour. It works differently from vitustotal or any av, it's a sandbox. Also you can watch the replay to see its a trojan.

**Comment by Cheoo21** [comment]
Also someone did call itnout for being a virus and advised ppl to not use ram. Quite surprised ur defending it.

**Comment by Wanwood1** [comment]
> Also someone did call itnout for being a virus and advised ppl to not use ram. Quite surprised ur defending it.

Just because some called it out doesnt mean its a virus, the source code is open, read it.
mr john or matt please block this guy so he shuts up and stops spreading misinfo and obviously trolling

**Comment by Cheoo21** [comment]
You just said, 
"if it was, someone would have looked at the source and spread the proof around, and we wouldnt be telling people to use Roblox Account Manager", Are you fucking stupid? its literally a fucking trojan, also did you even read what I just said? TRIAGE IS FUCKING DIFFERENT FROM A VIRUSTOTAL SCAN, TRIAGE USES A VIRUTUAL COMPUTER TO TEST WHAT THE VIRUS WOULD DO YOU FUCKING GOBSHITE, NOT JUST SCANNING THE FUCKING FILE, IF IT ISNT A VIRUS, then why did they locked down their discord to prevent 'misinformation' if they were so confident in it not being malicious then why are they so averse to an open discussion? get it? GET IT? ITS NOT FUCKING MISINFORMATION, I GET THAT THERES FALSE POSITIVE BUT I TESTED IT OUT ON A ACTUAL SANDBOX. why tf are YOU spreading misinformation? its been confirmed a trojan like launcher because it sends TCP packets to some random ahh location when the app is running. please delete this gobshite trying to get ppl ratted

**Comment by bluepilledgreat** [comment]
> You just said...

Shut the fuck up

**Comment by Wanwood1** [comment]
> You just said, "if it was, someone would have looked at the source and spread the proof around, and we wouldnt be telling people to use Roblox Account Manager", Are you fucking stupid? its literally a fucking trojan, also did you even read what I just said? TRIAGE IS FUCKING DIFFERENT FROM A VIRUSTOTAL SCAN, TRIAGE USES A VIRUTUAL COMPUTER TO TEST WHAT THE VIRUS WOULD DO YOU FUCKING GOBSHITE, NOT JUST SCANNING THE FUCKING FILE, IF IT ISNT A VIRUS, then why did they locked down their discord to prevent 'misinformation' if they were so confident in it not being malicious then why are they so averse to an open discussion? get it? GET IT? ITS NOT FUCKING MISINFORMATION, I GET THAT THERES FALSE POSITIVE BUT I TESTED IT OUT ON A ACTUAL SANDBOX. why tf are YOU spreading misinformation? its been confirmed a trojan like launcher because it sends TCP packets to some random ahh location when the app is running. please delete this gobshite trying to get ppl ratted

It is very obvious you are a troll, RAM is not a trojan or a virus and it has never been one. Im no longer going to be responding to you in hopes you shut up, never touch this github again or are blocked so you can no longer interact here.

**Comment by vvirtues** [comment]
> You just said...

Literally any and every app that accesses something online does that. You should see what chrome does

**Comment by Cheoo21** [comment]
> > You just said, "if it was, someone would have looked at the source and spread the proof around, and we wouldnt be telling people to use Roblox Account Manager", Are you fucking stupid? its literally a fucking trojan, also did you even read what I just said? TRIAGE IS FUCKING DIFFERENT FROM A VIRUSTOTAL SCAN, TRIAGE USES A VIRUTUAL COMPUTER TO TEST WHAT THE VIRUS WOULD DO YOU FUCKING GOBSHITE, NOT JUST SCANNING THE FUCKING FILE, IF IT ISNT A VIRUS, then why did they locked down their discord to prevent 'misinformation' if they were so confident in it not being malicious then why are they so averse to an open discussion? get it? GET IT? ITS NOT FUCKING MISINFORMATION, I GET THAT THERES FALSE POSITIVE BUT I TESTED IT OUT ON A ACTUAL SANDBOX. why tf are YOU spreading misinformation? its been confirmed a trojan like launcher because it sends TCP packets to some random ahh location when the app is running. please delete this gobshite trying to get ppl ratted
> 
> It is very obvious you are a troll, RAM is not a trojan or a virus and it has never been one. Im no longer going to be responding to you in hopes you shut up, never touch this github again or are blocked so you can no longer interact here.

womp womp cry harder imagine defending a trojan

**Comment by Cheoo21** [comment]
where is your proof that ram isnt a trojan, did you do your research or do you get paid money to defend ram?

**Comment by vvirtues** [comment]
None y'all are serious
You too dumb to look through the code or build it yourself so you call it a virus

**Comment by NabHeyka22** [comment]
> None y'all are serious You too dumb to look through the code or build it yourself so you call it a virus

He is right tho.
Just don't reply to this idiot.

**Comment by sigma-skibidi-mewing** [comment]
CALM THE FUCK DOWN WE ARE GETTING AWAY FROM THE POINT GO FIGHT SOMEWHERE FUCKING ELSE AND LEAVE MY GMAIL ACCOUNT IT BLOWS UP WHENEVER YOU GUYS ARE WHINING ABOUT STUFF GO FIND A PLACE TO ARGUEE

**Comment by bluepilledgreat** [comment]
lol
