### ISSUE TITLE
[BUG] hi when i open the app it starts as normel but crashs after 30 secs

### ISSUE THREAD

**Issue by mahantyj1** [pizzaboxer/bloxstrap#3079]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

Roblox opens fine, but a crash happens sometime later, and this happens consistently I have seen your website but nothing is working

### Bloxstrap Log

N/A

**Comment by Tomloyo** [comment]
bro
![image](https://github.com/user-attachments/assets/f0516903-9b0e-4b3e-910b-2ad1c03e6bca)

**Comment by mahantyj1** [comment]
Oh I thought it said I did answer truthfully to all the above checkboxes
sorry I am very bad at English

**Comment by Zacgamingpro1234** [comment]
Ok don't worry I will try to help you. Does this happen on bloxstrap only or on the official roblox client too?

**Comment by mahantyj1** [comment]
Both

**Comment by Zacgamingpro1234** [comment]
This isn't a bloxstrap bug then. What os are you using? (Windows 10,11 .ect) If you are using windows 11 try this, go to windows security.
![image](https://github.com/user-attachments/assets/1af5c3aa-09ec-4d85-910a-976b83d52bc1)
Now go to device security then core isolation. Disable Memory Integrity. This same issue happened to me and this fixed it. Why you might ask? Roblox released their anti-cheat update (hyperion), which crashed your game unless you have memory integrity disabled. This happens because hyperion tries to block some cheats but windows detects it as malicious and terminates the process.

**Comment by pizzaboxer** [comment]
Not a Bloxstrap issue

**Comment by mahantyj1** [comment]
oh..........................................................................................................
