### ISSUE TITLE
Deleted literslly the entirety of the folder it was in

### ISSUE THREAD

**Issue by Uncommom** [pizzaboxer/bloxstrap#314]
Uninstalled bloxstrap today to reinstall and it literally deleted the entirety of the folder it was in, and it included a lot of different games that I now lost progress in

**Comment by pizzaboxer** [comment]
What did you choose as your install location?

**Comment by Uncommom** [comment]
I know it was most likely my fault, but it was in the same folder as a lot of the games, I never had such issues before with anything so I didn't think something like that would happen, though it left out 2 random folders for some reason

**Comment by pizzaboxer** [comment]
So, from what happened. I think the problem is that you changed Bloxstrap's install location, but instead of setting it to its own independent folder, you set it as your entire games folder, assuming it would just handle it from that.

Yeah, I can't say I would've been able to forsee something like that happening.

If this just happened now, you should be able to recover most of the files (and save data) using something like Recuva, since most of the data should still actually be on the drive. 

In a way, it was your fault for not realizing that Bloxstrap would assume the entire games folder as its install location, but in a way it's mostly mine for not making it clearer or handling it, which I do seriously apologize for. I'll make this less of a problem in the next version.

**Comment by Uncommom** [comment]
Thanks, and yeah I will try to recover the files
Have a good day!

**Comment by pizzaboxer** [comment]
Continuing to work on improvement - hopefully this warning is clear and effective enough?

![image](https://github.com/pizzaboxer/bloxstrap/assets/41478239/4ba7f2f8-6df2-46a5-9d5e-6eaa89b3ea0f)
