### ISSUE TITLE
Somehow Max out my CPU usage but not my IGPU or GPU

### ISSUE THREAD

**Issue by UmmmIdontknowmyname** [pizzaboxer/bloxstrap#344]
It does something to max out the cpu and bottleneck the hole system
And from task manager I can see Bloxtrap use up 45%cpu

**Comment by pizzaboxer** [comment]
Bloxstrap is using 45% CPU? Can I see a screenshot please? Also, out of curiosity, what CPU do you have?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.

**Comment by neprao** [comment]
yup same

**Comment by pizzaboxer** [comment]
If so, do what I asked OP earlier

**Comment by KOMKO190** [comment]
Since neither the OP nor the other guy posted more info, I'll do it.

I also noticed heavy CPU usage when using bloxstrap roblox bootstraper over the regular one. It's weird and even happens when lowering my graphics settings (I disable the 1-21 and enabled 1-10, made the graphics 7 and still the same thing -> before it was just fine on 10).
![image](https://github.com/pizzaboxer/bloxstrap/assets/55060846/26060e87-2c19-4f51-98fd-c6cb206b64d3)
Later, I will deinstall Bloxstrap and show you screenshots on the regular bootstraper so you can see the difference.

Also, I'm not sure if OP is reffering to Roblox Game Client or the Bloxstrap app itself, but the Bloxstrap usage looks something like this:
![image](https://github.com/pizzaboxer/bloxstrap/assets/55060846/a0e760a5-00cc-4577-a428-e746c9cc4aa9)

**Comment by Zapnagor** [comment]
I'm not the most active user on Github but i would like to add to this conversation as I've also noticed this.
(don't mind the other programs)

This is with Bloxstrap running:
![Screenshot_1](https://github.com/pizzaboxer/bloxstrap/assets/133076365/2bd2cb08-3bfd-4f9f-83f0-9a72e5a7d313)

Than i launched Roblox without bloxstrap and its like:
![Screenshot_2](https://github.com/pizzaboxer/bloxstrap/assets/133076365/c5cd4f12-0003-4748-912a-e6ff4705b1a4)

It makes me wonder what Bloxstrap is utilizing/doing in the background for this amount of extra cpu usage to happen.
And would be nice if there would be some kind of optimization to not cause this since some games become unplayable from the sudden frame drop from 144 to 36 at times.

sidenote: I'm running with an RTX 3070 TI and an Intel i5-11400F
