### ISSUE TITLE
[Suggestion] Allow an option to abort launching Roblox

### ISSUE THREAD

**Issue by NikoYTRBLX** [pizzaboxer/bloxstrap#346]
![image](https://github.com/pizzaboxer/bloxstrap/assets/38755801/3303b4a4-68c6-4a0b-aa10-e49178b667e8)
Currently, if you're on an old channel and launch Roblox, you're essentially forced to launch Roblox no matter what. It's one or the other, and I don't want to use either. Allow an option to cancel launching Roblox in the prompt that appears or even to go back to the Bloxstrap Menu and change the channel from there — just a QoL suggestion.

Same could be probably done when launching Roblox normally, actually!

**Comment by pizzaboxer** [comment]
I'm a little confused about the use case. If you just made the choice to launch Roblox, why would you then want to not launch Roblox? Typically, the whole launch process only takes like four seconds, which is why there's no cancel button. It's pointless. The cancel button only shows during installation/update because those actually go on for a long amonunt of time.

**Comment by NikoYTRBLX** [comment]
Okay, honestly, now that I've put more thought into it, you're right. It doesn't have much point and you could just kill Roblox's process and then change the settings from the Bloxstrap Menu right after. Having the abort button there would save only a few seconds that didn't need to be saved.
