### ISSUE TITLE
[BUG] *Error with cursor and Roblox loading. Last Version Issue

### ISSUE THREAD

**Issue by vizevScripts** [pizzaboxer/bloxstrap#3706]
### Bloxstrap Version

v2.8.1

### What problem did you encounter?
I can't play any games in Roblox. Please fix it.
Also, my cursor is invisible and the games played bar is also invisible.

![help me](https://github.com/user-attachments/assets/e542a108-9660-4013-a2d0-62cccc5d6212)

**Comment by Nonolelase** [comment]
It's look like evreryone has the same problem.. I got it too

**Comment by Wanwood1** [comment]
Roblox issue, make sure the location and drive bloxstrap is installed in doesnt have any special characters, including your windows user

**Comment by snipers14** [comment]
Same thing here, games don't show invisible cursor and font looks different

![RobloxScreenShot20241108_040232068](https://github.com/user-attachments/assets/1b9cd79d-ac17-478b-9cd0-4b05bb4cb5ab)

**Comment by hypno-maker** [comment]
> Roblox issue, make sure the location and drive bloxstrap is installed in doesnt have any special characters, including your windows user

my windows user is максим

**Comment by killaheelz** [comment]
Eng: The problem is that when installing Bloxtrap'a, the root folder is put on the user, and many people have it contains unsupported characters (for example, the Russian alphabet), reinstall Bloxtrap way, where there will be no such characters.

Rus: Проблема в том, что при установке Bloxtrap'а, корневая папка ставится на юзера, а у многих он содержит не поддерживаемые символы (к примеру русский алфавит), переустановите Bloxtrap путём, где не будет фигурировать таких символов.
