### ISSUE TITLE
Can't run bloxstrap at all

### ISSUE THREAD

**Issue by Poweridium** [pizzaboxer/bloxstrap#408]
While trying to run bloxstrap I got this error I tried installing a different version but got the same thing.

No idea how this happened or how to replicate it

![Screenshot 2023-07-21 174654](https://github.com/pizzaboxer/bloxstrap/assets/140212283/31ec3be8-737a-4294-88d2-dde4836a5a8a)
![Screenshot 2023-07-21 174702](https://github.com/pizzaboxer/bloxstrap/assets/140212283/ca783898-20d9-4af3-8f43-4df248fccb25)
[Bloxstrap_20230714T182330Z.log](https://github.com/pizzaboxer/bloxstrap/files/12134851/Bloxstrap_20230714T182330Z.log)

**Comment by pizzaboxer** [comment]
Do you use RoGold?

**Comment by Poweridium** [comment]
Yes I do

**Comment by pizzaboxer** [comment]
That error only happens if you launch a game through one of RoGold's features because it launches Roblox twice. You can just ignore the error as Roblox will launch and work just fine anyway. Though, 2.4.0 was supposed to make it less of a problem, unless you happen to be using an old build. I'll look at it later.

**Comment by Poweridium** [comment]
Alright thanks for all the help
