### ISSUE TITLE
My computer is on fire after the update 2.4.0

### ISSUE THREAD

**Issue by Tortida2** [pizzaboxer/bloxstrap#430]
When I use bloxtrap, my gpu utilization is between 50% to 65% and my gpu temperature is between 70°C to 80°C or between 158°F to 176°F
![Screenshot (352)](https://github.com/pizzaboxer/bloxstrap/assets/140476371/47290587-a606-4b47-82d2-33013dfa7066)

**Comment by pizzaboxer** [comment]
And what's your GPU usage in Task Manager like? I doubt it's related to Bloxstrap.

**Comment by WaviestBalloon** [comment]
Have you tested the same game with and without Bloxstrap installed?

**Comment by Tortida2** [comment]
![With-Bloxtrap](https://github.com/pizzaboxer/bloxstrap/assets/140476371/1ba2c0bc-abc1-4dd9-a748-10b9a0b61a44)
![Without-Bloxtrap](https://github.com/pizzaboxer/bloxstrap/assets/140476371/9c09781f-df70-4fdd-85e0-751c2bfcf824)
(When I took these screenshots my room was cold so the gpu temperatures were cooler)

**Comment by pizzaboxer** [comment]
Actually, I think I might know why. Is your display scaling greater than 100%?

**Comment by Tortida2** [comment]
My display scaling is on 200%

**Comment by pizzaboxer** [comment]
Okay, that makes a lot more sense. From the release notes:

> [FastFlag] Added flags for fixing DPI scaling, which are automatically set.

Roblox decreases the rendering quality based on your display scaling. This disables that, because I kind of just assumed that anybody who actually needed display scaling probably had powerful enough hardware to drive it anyway. And indeed, it looks like you do, since you're only using 44% of you're GPU.

**Comment by pizzaboxer** [comment]
Oh, forgot I already opened an issue for this - #440
