### ISSUE TITLE
Avatar Editor Glitch

### ISSUE THREAD

**Issue by sha4owz** [pizzaboxer/bloxstrap#450]
Ok so i just wanted to say THANK YOU for adding this coo, feature! But sadly there is a small error. The character is on the edge of the carpet when the lights and SFX is aiming for the center of the carpet. Basically, the player is supposed to be in the middle of the carpet where the spotlight it. Also you shouldn't be able to see white or the edge of the floor. So try zooming in.

Hope this didn't come across rude and once again THANK YOU for the feature! <3 
![image](https://github.com/pizzaboxer/bloxstrap/assets/138281770/f817f9c9-d918-419a-9491-753fbb4bba67)

**Comment by pizzaboxer** [comment]
> The character is on the edge of the carpet when the lights and SFX is aiming for the center of the carpet.

Yeah, positioning for R6 and R15 characters are different. I'll fix it to be R15 since it's what everyone uses.

> Also you shouldn't be able to see white or the edge of the floor. So try zooming in.

But then you wouldn't be able to see your avatar. Also, it wasn't designed for this camera angle, so there's that. Only way to "fix" it would be to modify and extend the map, which I'd rather not do.
