### ISSUE TITLE
i need help with dx11

### ISSUE THREAD

**Issue by savegemastro** [pizzaboxer/bloxstrap#469]
when I try to use exclusive Fullscreen it got back to windowed mode do u know how to fix?

**Comment by pizzaboxer** [comment]
Are you using any overlays or anything?

**Comment by savegemastro** [comment]
no


> Are you using any overlays or anything?

**Comment by pizzaboxer** [comment]
I should mention that exclusive fullscreen only does that if another window pops on screen, as that's what it's supposed to do. Some other window or something is likely trying to show itself, which is probably why Roblox is doing that. That's just my guess though. I'll close this since this isn't a Bloxstrap problem.

**Comment by savegemastro** [comment]
okay thx for telling e that
