### ISSUE TITLE
Font issue

### ISSUE THREAD

**Issue by JustConey15** [pizzaboxer/bloxstrap#524]
Apply custom font doesn't apply to every font 
![image](https://github.com/pizzaboxer/bloxstrap/assets/141701527/5aa8d726-e002-4770-bbdf-44b940e71ffb)

**Comment by 1011025m** [comment]
Roblox has [fonts that they put on the marketplace](https://create.roblox.com/marketplace/fonts) and developers can choose to use them. These are downloaded **on demand**, meaning they don't live inside the versions folders. It'll be difficult to apply a custom font file to these ones at runtime

**Comment by pizzaboxer** [comment]
The mod preset only applies to the fonts that come bundled with Roblox, which are these here. There's no way for me to alter any fonts that are loaded from the marketplace, sorry. Since the built-in fonts are what's used most of the time, this shouldn't be that big of a problem.

![image](https://github.com/pizzaboxer/bloxstrap/assets/41478239/1094e3e9-6dc0-403f-ba4c-541860edfbfa)
