### ISSUE TITLE
i keep getting the unrecoverable error.

### ISSUE THREAD

**Issue by Jiggomase** [pizzaboxer/bloxstrap#534]
this is a general roblox client issue, i have uninstalled multiple time, cleared my temp files, disabled full-screen optimizations, launched as admin, etc. nothing ever worked. though this client would fix it, but no. anyone got any fixes other than the ones i have already tried? this started happening around when byfron was added btw.

edit: i have also tried creating a memory dump (it was 200+ mb btw), but i do not know what to do with it since there is no website to send it to.
![image_2023-08-10_114525929](https://github.com/pizzaboxer/bloxstrap/assets/127654049/8d8f7929-b7d3-40c1-9bdd-683299be08b9)

**Comment by pizzaboxer** [comment]
>  this started happening around when byfron was added btw.

Yeah, this error is coming from Hyperion. There isn't really much I can do to help you on this, but my best advice is to just ensure that no programs running on your computer are trying to mess around with the Roblox game client process, since that's the condition this specific error typically appears in.

> but i do not know what to do with it since there is no website to send it to.

It means the Roblox support website.

I'll close this since this isn't a Bloxstrap problem.
