### ISSUE TITLE
Bloxstrap and Roblox VC Issue

### ISSUE THREAD

**Issue by lugolol** [pizzaboxer/bloxstrap#541]
The Roblox Voice chat red triangle appears to be on when the game is launched with Bloxstrap. I tried uninstalling it and installing to test it and it seems Bloxstrap is the reason why my VC is disabled when I join a game.

edit: it seems that is happening with 3rd party Roblox apps as well

**Comment by pizzaboxer** [comment]
Red triangle?

**Comment by lugolol** [comment]
[https://cdn.discordapp.com/attachments/1129286836523630642/1140328120424091841/image.png](url)

**Comment by pizzaboxer** [comment]
Yeah, I just realized, I don't have voice chat myself. And because of that, I can't really confirm, but this is definitely the first I've heard of this. It might be a bit of a long shot, but you should check to see if Windows is denying Microphone access to Roblox in Windows settings. Just search "microphone privacy settings".

Also, what 3rd party apps?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.

**Comment by OwariNoKenshi** [comment]
i'm having this issue too  and i cant find anything in microphone privacy settings about bloxstrap or roblox

**Comment by pizzaboxer** [comment]
> and i cant find anything in microphone privacy settings about bloxstrap or roblox

It should be there, show the list of programs that are listed in the settings.

**Comment by OwariNoKenshi** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/86060124/91179e40-504a-4594-a323-e3da55037189)
![image](https://github.com/pizzaboxer/bloxstrap/assets/86060124/d926c4c2-c95a-4d5e-a421-b254eb951709)
it constantly says still connecting but as soon as i close bloxstrap and reopen roblox it immediatly works.

**Comment by pizzaboxer** [comment]
This is a completely different problem though, this is about voice connection.

**Comment by OwariNoKenshi** [comment]
after a while of connecting i get the red triangle in the corner of the voice chat icon, because it can't connect

**Comment by pizzaboxer** [comment]
Oh, I thought the red triangle only happens if it can't find an input device. Does it happen for both?

Anyway, see if it happens without Bloxstrap too. https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by kychet** [comment]
> Oh, I thought the red triangle only happens if it can't find an input device. Does it happen for both?
> 
> Anyway, see if it happens without Bloxstrap too. https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap
I also have a problem where I can't hear anyone elses vc and it's honestly annoying and fustrating, I have to uninstall bloxstrap just to use vc..

**Comment by pizzaboxer** [comment]
>  I also have a problem where I can't hear anyone elses vc and it's honestly annoying and fustrating, I have to uninstall bloxstrap just to use vc..

The problem is only that you can't hear other people? Please clarify if:
- you're able to actually use voice chat in game
- changing your output device in the escape menu does not work
- that you're actually able to hear in-game sounds

If it's "yes" to all of those questions, then upload your configuration please:
https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration
