### ISSUE TITLE
Mouse Cursor Enhancement with Presets

### ISSUE THREAD

**Issue by fehh44** [pizzaboxer/bloxstrap#555]
Each preset shows you a preview of the mouse cursors like ArrowCursor and ArrowFarCursor before you apply them.

**"But how should i change it?"**

Just hit a cursor preview, and a window pops up asking for an image for that cursor. Once you've got your image, the preview and the actual cursor file in the mods folder change to match your style. That's how you see exactly what your new cursor brings.

Change up both images, and a "Save" button shows up. Hit the button, type in a name for the preset, and your new cursor and its new name are saved as a preset. And then you can rename, delete, or shuffle them.

**Here's how it would look like:**
![image](https://github.com/pizzaboxer/bloxstrap/assets/134188550/9320f73b-330e-4287-b4cd-ee73b1bdd5a4)

**Comment by pizzaboxer** [comment]
I disagree with doing this. If I'm going this way, I'd need to add a similar thing for every single other thing that can possibly be modded. That's why there is such a huge emphasis on using the mod folder for adding your own stuff - because it gives you the greatest flexibility and freedom imaginable.

That being said, despite my best efforts with the wiki guide and everything, I'm not exactly making it very straightforward for people to add their own stuff right now. Mainly because it's kind of difficult for people to know what to get started with. I'll probably work on updating the help page to lay out the general folder structure, as well as noting down the file paths of most interest.

**Comment by ImMejor35** [comment]
mod manager?
