### ISSUE TITLE
Roblox App Removal

### ISSUE THREAD

**Issue by Profility** [pizzaboxer/bloxstrap#58]
The ROBLOX App has been bugging for me awhile especially because it takes so much CPU when open in the background.

Can there be a feature that removes the app completely?

**Comment by pizzaboxer** [comment]
This used to exist, but [had to be removed](https://github.com/pizzaboxer/bloxstrap/issues/40).

If I recall correctly, there was later discovered to be a workaround that you can do by going to your Bloxstrap mod folder and creating a blank file in `ExtraContent\places\Mobile.rbxl`.

I didn't add this as a feature at the time because I didn't think the workaround would work for that long, but seems like it's actually going to work fine for a while.

For now, you can just do what I've stated above, but in the next version I can add this as a built-in mod setting.

**Comment by Profility** [comment]
Tried the workaround and it works great; the ROBLOX app doesn't launch anymore whenever I exit a game, thanks
