### ISSUE TITLE
Roblox crashing instantly without any message

### ISSUE THREAD

**Issue by Cyber2525** [pizzaboxer/bloxstrap#643]
https://github.com/pizzaboxer/bloxstrap/assets/83342792/fcf777b8-3a08-4adf-9a4d-90659c474c82

**Comment by pizzaboxer** [comment]
Have you read https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch?

**Comment by rblxSioFi** [comment]
This issue is happening to me too. I downloaded the Roblox launcher fresh from the roblox website and tried running it, which seems to work fine. Whenever I go to launch through Bloxstrap, Roblox never opens and only shows the launcher window with the loading bar. I did read the article you posted, but to no avail. (I don't use a lot of background processes that tamper with other processes either, I try to keep that minimal).

Is there any fast flags that should be disabled to see if it fixes the issue? From what I'm aware Bloxstrap doesn't apply fast flag changes if they're not correct (example, inputting the wrong fast flag name causes no fast flags to be changed at all) so I would sort of expect that to not be an issue here, but I thought I'd ask anyway. I figured you pizzaboxer, would be more knowledgeable in this area.

**Comment by rblxSioFi** [comment]
roblox updated through the ZIntegration channel today. Seems that it fixed the issue with bloxstrap. Maybe roblox just needed to be reinstalled.

**Comment by pizzaboxer** [comment]
> roblox updated through the ZIntegration channel today. Seems that it fixed the issue with bloxstrap.

now do you see why i removed the dropdown

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
