### ISSUE TITLE
Game Freeze.

### ISSUE THREAD

**Issue by MeGoddess** [pizzaboxer/bloxstrap#649]
After a while of playing, roblox itself completely freezes and does not respond in any way. I have to unload the application from the task manager. This happens almost always.

https://github.com/pizzaboxer/bloxstrap/assets/144396571/3eb4c80e-60b1-4400-9683-a0a1d2668bdd

**Comment by pizzaboxer** [comment]
Are you able to provide a more specific timeframe on how long it takes for this to happen? Also, can I see your FastFlag list? Open the menu, go to the FastFlags tab, open the editor, and show a picture of the whole list.

**Comment by MeGoddess** [comment]
![20230909_192710](https://github.com/pizzaboxer/bloxstrap/assets/144396571/85c9f5b7-1c91-47fb-b599-b739bd4b8bd5)

In about two to seven minutes.

**Comment by pizzaboxer** [comment]
I said to open the editor.

**Comment by MeGoddess** [comment]
this?
![20230909_193052](https://github.com/pizzaboxer/bloxstrap/assets/144396571/31853ce7-3357-4d9f-af44-2dee80591c9b)

**Comment by pizzaboxer** [comment]
Okay, that seems good. Have you also checked to see if this happens only with Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by MeGoddess** [comment]
Yes, this only happens with Bloxstrap. With the regular roblox client everything is normal.

**Comment by pizzaboxer** [comment]
You could try setting your rendering mode to Automatic, and your framerate limit to 0. See if doing those two changes anything.

**Comment by MeGoddess** [comment]
Okay, I'll give it a try. I will test it in several games.

**Comment by MeGoddess** [comment]
It became even worse. in addition to freezing Roblox itself, it became problematic to go to the Task Manager to remove a task from Roblox and finish its work.

**Comment by pizzaboxer** [comment]
How about if you disable activity tracking?

**Comment by MeGoddess** [comment]
I turned it off from the beginning.

**Comment by pizzaboxer** [comment]
Well, I can't really think of what else would be causing it since at this point Bloxstrap should be functioning exactly like how the official launcher does. You could also try forcing a Roblox reinstallation? Go to the Behaviour tab, scroll to the bottom, option should be there. Enable it, save, and try and join.

**Comment by MeGoddess** [comment]
Honestly I reinstalled both Bloxstrap and Roblox using the Revo uninstaller utility. And the result is still the same.

**Comment by pizzaboxer** [comment]
Well, I'm not really sure what to say because at this point Bloxstrap should be working exactly like the official launcher, but I'll try and do some more troubleshooting here.

Can you go to where Bloxstrap is installed (open the menu, installation tab, open installation folder), go inside the "Versions" folder, go inside "version-xxxxxxxxxxxxxxxx", and launch RobloxPlayerBeta.exe directly? See if the problem happens with just that.

**Comment by MeGoddess** [comment]
same thing
https://github.com/pizzaboxer/bloxstrap/assets/144396571/40bea83d-78d7-4257-b44e-779078d6dcdd

**Comment by pizzaboxer** [comment]
This time, delete the "ClientSettings" folder, then launch RobloxPlayerBeta.exe again.

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
