### ISSUE TITLE
[Feature Request] Add Feature that download texture pack from gamebanana and apply

### ISSUE THREAD

**Issue by ImLoadingUuU** [pizzaboxer/bloxstrap#658]

**Comment by GoingCrazyDude** [comment]
i dont think this is possible

**Comment by ImLoadingUuU** [comment]
Its possible.
https://github.com/ImLoadingUuU/RoMod-Lite/blob/main/src/library.ts

i remember this is the part that download mod file  and extract

https://github.com/ImLoadingUuU/RoMod-Lite/blob/main/src/applyer.ts

this one apply texture pack

works perfectly but its design for macOS bur i sold my mac to buy a windows

**Comment by GoingCrazyDude** [comment]
oh i thought you meant something else
yeah this would be a cool feature ngl

**Comment by ImLoadingUuU** [comment]
some texture from gamebanana is folder inside folder . so you may need add texture pack checker

**Comment by pizzaboxer** [comment]
Circling back to this idea, I don't think this is viable because there's no telling how a mod may be packaged. It could be packaged as just the bare files with the directory specified in the description. I don't really think there's a way to handle the automatically, and I'm sure this is best suited to being handled manually.

**Comment by user1126s** [comment]
Just add a button that downloads some good mods and places them in c:/users/(username)/Bloxstrap/ModDownloads and add a button to open that folder because  it's a pain to find good mods in gamebanana, maybe choose some from your discord server and potentially make a feature like this for flags Linked with your discord so you can approve fflags and they appear in the menu for the user to choose from?

**Comment by pizzaboxer** [comment]
> Just add a button that downloads some good mods and places them in c:/users/(username)/Bloxstrap/ModDownloads and add a button to open that folder

What's the point of that? How is that any different to just browsing the website and downloading a zip file yourself?

**Comment by user1126s** [comment]
The website lags on my PC even with 4gb ram and SSD and using every browser since it just shows so much ads and it is hard to find some actual good packs
