### ISSUE TITLE
Idea: separate mods folders

### ISSUE THREAD

**Issue by MehKako** [pizzaboxer/bloxstrap#71]
Option to have different mods installs. 

if you have no mods then it would start like normal but if you have some folders it would start with a list to choose from before starting roblox.

Useful if you want to switch between a modified roblox folder or the regular one.

**Comment by pizzaboxer** [comment]
I'm... not entirely sure that I see the purpose of this? Especially given that it has to be something frequent/important enough to be prompted with at every launch. If you want to switch between what mods you want rather than having them all at once, copy and pasting them in and out of another folder seems sufficient.
