### ISSUE TITLE
[BUG] When i change my fps counter to 240 its still stays 165 like my monitor

### ISSUE THREAD

**Issue by Beyroz** [pizzaboxer/bloxstrap#796]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

So even if i change the fps cap to 240 its still capping it at 162-165 idk why this is happening pls fix

**Comment by pizzaboxer** [comment]
Are you using exclusive fullscreen?

**Comment by BokBoy** [comment]
@Beyroz, If you are getting 240 FPS, it is capped by the amount the GPU can handle and what your display can show. Even if you set your fps to 240 but your monitor can only show 165, it will show 165.
The FPS shown is the weakest link between your GPU, Cable and Monitor. Your GPU can probably handle 1000fps but it depends on the speed of the cable and connectors to bring that. Then, there is the monitor restriction otherwise the monitor would take tonnes of power and not be able to continue. 
If it doesn't make sense, I cant explain it better, sorry.

**Comment by jaynardd** [comment]
Fellas how do i fix my bloxstrap not capping my fps no more

**Comment by BokBoy** [comment]
> Fellas how do i fix my bloxstrap not capping my fps no more
> 
> 

Open a new issue, what you said is way to broad.

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.

**Comment by PringleKitten** [comment]
Same here, I'm not even in exclusive fullscreen, heck I even used windowed mode, my fps is capped at 240 even though I set it to 999. Every other game uncaps so it's not my fault. I've gotten 6000fps in osu so.

**Comment by pizzaboxer** [comment]
> my fps is capped at 240 even though 

You're not having the same issue then. Their issue is that they can't reach 240.

Roblox is intentionally limiting you to 240 for good reason. You can temporarily get past it, but I wouldn't recommend doing so if you have no real need.

**Comment by PringleKitten** [comment]
> > my fps is capped at 240 even though
> 
> You're not having the same issue then. Their issue is that they can't reach 240.
> 
> Roblox is intentionally limiting you to 240 for good reason. You can temporarily get past it, but I wouldn't recommend doing so if you have no real need.

I found out you have to disable their limit 240 flag option
