### ISSUE TITLE
[BUG] I can't close out of full screen in the 2.5.4 update.

### ISSUE THREAD

**Issue by BloxyReimu** [pizzaboxer/bloxstrap#913]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I was playing Roblox the other day, and I wanted to use true full screen so I did, but now I can't close out of it for some reason because of the new 2.5.4 update that released. It didn't even occur to me during when I uninstalled bloxstrap. Maybe you messed up true fullscreen with the graphics rendering change. It wasn't even unstable for me so why change it. Now I can't even unfullscreen Roblox because of this change. Can you look into this for me? I found this to be a pretty useless change that didn't need to happen since people actually used it a lot.

**Comment by pizzaboxer** [comment]
> It wasn't even unstable for me so why change it.

[Cool, I don't care about you.](https://github.com/pizzaboxer/bloxstrap/issues?q=is%3Aissue+is%3Aclosed+vulkan+crash)

Regardless, I'm not entirely seeing how this would be related to the removal of the rendering mode option. But since we're here, what were you using prior to the update?

**Comment by BloxyReimu** [comment]
Vulkan, I used it for true fullscreen and the better rendering

**Comment by pizzaboxer** [comment]
Well, I can't replicate this bug because Vulkan doesn't work for me. lol.
You can temporarily re-enable Vulkan by setting the `FFlagDebugGraphicsPreferVulkan` flag to `True` in the flag editor, then see if you can un-fullscreen from there. Then you can remove it afterwards or opt to keep using it (but be mindful about the fact you have it enabled if Roblox breaks in the future). Let me know if that doesn't work.

**Comment by BloxyReimu** [comment]
Nope. It didn't work. True Fullscreen might've broke this update.

**Comment by pizzaboxer** [comment]
Were you able to re-enable Vulkan by setting the flag?

**Comment by BloxyReimu** [comment]
Yes.

**Comment by pizzaboxer** [comment]
Okay, I just remembered why this happens since I remember someone opening a previous report for this. If Vulkan has really been enabled the whole time then what's happening here sort of makes sense.
Disable Vulkan by deleting the flag. See if you're able to do anything then.

**Comment by BloxyReimu** [comment]
I tried it without vulkan before I uninstalled bloxstrap and reinstalled it, and it doesn't work. It doesn't have to do with rendering. True Full screen might've broke, that's my theory.

**Comment by pizzaboxer** [comment]
I mean, at this point you can try and reset your fullscreen settings by deleting or temporarily moving both `GlobalBasicSettings_13.xml` and `GlobalSettings_13.xml` that's located inside `%localappdata%\Roblox`.

**Comment by BloxyReimu** [comment]
I believe like the only way to fix this issue is to uninstall bloxstrap. Yeah this is a stupid bug that shouldn't have happened.

**Comment by pizzaboxer** [comment]
Overall, I'm more confused than ever because some things here don't add up from what you've told me.
Updating was supposed to automatically disable Vulkan, but you say that never happened. If it was always enabled throughout, then what would have even broken it?
Fullscreen still taking effect when disabling Vulkan and using Direct3D would also mean that Roblox itself is handling it normally with F11, where I don't really see any reason for it to not work. What does the fullscreen option in the escape menu show?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
