### ISSUE TITLE
Title bar text misalinged

### ISSUE THREAD

**Issue by nodomw** [pizzaboxer/bloxstrap#92]
Only started happening now with the new Fluent UI. Does not happen for the native Win32 windows.
![kép](https://user-images.githubusercontent.com/47635446/219880007-d8c36522-73a5-4b74-a568-7a11020d9942.png)
![kép](https://user-images.githubusercontent.com/47635446/219880009-59854f8f-1fae-439f-ba21-f72c9778284a.png)
![kép](https://user-images.githubusercontent.com/47635446/219880026-62307615-4fff-42d8-ab5e-68fd72e1bb5a.png)

**Comment by pizzaboxer** [comment]
Oh, didn't know the title bar colour shows. I was expecting it to match the rest of the UI background (see the [screenshots in the README](https://github.com/pizzaboxer/bloxstrap#screenshots) for what I mean).
I'll have this fixed in a future patch, thanks for reporting.

**Comment by nodomw** [comment]
Oh, I have StartAllBack installed and it has an option to color every element with the accent color that windows doesn't by default. Didn't know it wasn't meant like that lol

**Comment by pizzaboxer** [comment]
This only happens with StartAllBack? That helps to know, thanks!

**Comment by pizzaboxer** [comment]
Nope, it's because of Windows 11's global titlebar colour setting. Anyway, my fix doesn't look perfect, but I've tried to make look as good as possible without sacrificing the Mica.
![vmware_qvioclQ73V](https://user-images.githubusercontent.com/41478239/219902007-387c75e3-4398-4fac-99bf-631af9b1f69c.png)
![vmware_oUKaN7PXiY](https://user-images.githubusercontent.com/41478239/219901999-c032cbec-82a7-4722-8b05-b138ddf3104f.png)
At least, until WPF UI publishes a fix for it (lepoco/wpfui#487).
